- src/components/buttons/delete-button/delete-button.js
- src/components/dialog-window/dialog-window.js
- src/components/editor/editor.js
- src/pages/business-pages/business-page-form/business-page-form.js
-wrong click handler property (dialog window)
-Quill duplicates empty paragraph on init
> Quill and dialog window fixes

- src/components/error-boundary/error-boundary.js
- src/components/error-boundary/index.js
- src/pages/error-page/error-page.js
- src/redux/error/error.actions.js
- src/redux/error/error.reducer.js
- src/redux/error/error.types.js
- src/routes/routes.js
Add error boundary for Admin panel
- routes
- boundary
- redux
> Error boundary Admin

- src/configs/statuses.js
- src/pages/error-page/error-page.js
- src/redux/error/error.reducer.js
- src/redux/root.reducer.js
Add error boundary for Admin panel
- change Error Message to "Сталася помилка"
> Error boundary: error information

- src/components/news-form/news-form.js
- src/pages/news/news-add/news-add.js
- src/pages/products/product-add/products-add.js
- src/pages/products/product-edit/product-edit-form/product-edit-form.js
- src/pages/users/users-details/users-details.js
> fix:path #242

- src/components/colors-autocomplete/colors-autocomplete.js
- src/components/colors-autocomplete/colors-autocomplete.styles.js
- src/components/colors-autocomplete/index.js
- src/components/colors-bar/colors-bar.js
- src/components/material-form/material-form.js
- src/pages/material/material-details/material-details.js
- src/pages/material/material-page/material-page.js
- src/pages/material/material-page/material-page.styles.js
- src/redux/color/color.operations.js
- src/redux/material/material.operations.js
- src/utils/use-material-handlers.js
https://github.com/ita-social-projects/horondi_admin/issues/389
> implement multiple colors adding to material

- .github/workflows/main.yml
- Dockerfile
- azure-pipelines.yml
Lock NodeJS version for CI pipeline and CD build container
> Lock NodeJS version

- src/components/forms/news-form/news-form.js
- src/pages/news/news-page.js
small fix with image and refactor
> News page fix

- src/components/forms/material-form/material-form.js
- src/components/forms/material-form/material-form.styles.js
- src/configs/purpose-enum.js
> add purpose drop-down

- src/components/forms/material-form/material-form.js
- src/components/forms/pattern-form/pattern-form.js
- src/pages/model/constructor/constructor-page/constructor-page.js
- src/pages/model/model-page.js
- src/pages/pattern/pattern-page.js
- src/redux/model/model.operations.js
- src/redux/pattern/pattern.operations.js
- src/redux/products/products.operations.js
fix admin material and pattern page on add and receive  data
>  fix admin material and pattern page

- src/components/forms/pattern-form/pattern-form.js
> fix pattern form

- src/components/forms/contacts-form/contacts-form.js
- src/components/forms/news-form/news-form.js
- src/configs/form-regexp.js
- src/configs/labels.js
Language panel for contact page
> Language panel for contacts

- src/components/forms/size-form/size-form.js
- src/configs/titles.js
> fix translations

- src/containers/table-container-generator/table-container-generator.js
- src/containers/table-container-generator/table-container-generator.styles.js
Remove capitalization from tables
> fix capitalise letters on pages #613

- .github/pull_request_template.md
> add checkbox with linking to issue

- src/components/forms/model-form/model-form.js
- src/components/forms/model-form/model-form.styles.js
- src/configs/labels.js
- src/configs/styles.js
- src/redux/model/model.operations.js
Fixed:
1) Priority now have number type
2) Label now don`t overrides input (but I need to more ivestigate Material UI to make this select similar to others)
3) Filled business-page with valid photos
4) Model now receives array of ID`s instead of size array
> fixed some bugs

- src/components/forms/category-form/category-form.js
- src/components/forms/category-form/category-form.styles.js
- src/components/forms/language-panel/language-panel.js
- src/configs/error-messages.js
- src/pages/login/login-page.js
- src/redux/auth/auth.sagas.js
Chaged login error message on "/loginPage".
Add "maxValue" on "/categoryPage"
> Fixed login error message and category validation

- src/components/forms/comment-form/tests/comment-form.test.js
- src/components/forms/comment-form/tests/comment-form.variables.js
Added unit tests for comment-form component. Closes #605
> Wrote Enzyme tests for Comment form #605

- src/configs/menu-categories.js
> added contacts

- src/configs/labels.js
- src/pages/contacts-page/contacts-edit/contacts-edit.js
Fixed that the data from DB appears in the form.
> fixed initial values in the form

- src/components/forms/language-panel/language-panel.js
- src/components/forms/model-form/model-form.js
- src/configs/error-messages.js
- src/configs/form-regexp.js
- src/validations/models/model-form-validation.js
Added some validations for inputs on model create/edit page
> added input validations for models

- src/components/forms/business-page-form/business-page-form.js
- src/configs/error-messages.js
- src/configs/index.js
- src/configs/labels.js
- src/utils/business-page-form.js
- src/utils/use-business-handlers.js
Have updated language panel on business page accordingly to the new UI design.
> Update language panel

- src/pages/sizes/tests/mockStoreReturner.js
- src/pages/sizes/tests/sizes.test.js
- src/pages/sizes/tests/sizes.variables.js
Adds working enzyme tests for component 'Sizes' of folder pages.
Closes #604
> added enzyme tests for Sizes page

- src/configs/regexes.js
- src/pages/order-item/tabs/delivery-details/ukrpost/ukrpost.js
- src/redux/orders/orders.operations.js
- src/redux/orders/orders.reducer.js
- src/utils/handle-orders-page.js
- src/utils/order.js
Added fields 'region' and 'district' to add order
Make region and district to be displayed in the form fields when order is edited
> Added fields 'region' and 'district' to add order

- src/pages/main-page/main-page.js
- src/pages/orders/orders-page.js
> fixed date view

- src/components/nav-bar/nav-bar.js
Fixed visibility of burger menu on login page
> fixed menu-burger visualize on login page

- src/redux/comments/tests/comments.actions.test.js
- src/redux/comments/tests/comments.sagas.test.js
- src/redux/contact/tests/contact.sagas.test.js
- src/redux/material/tests/material.saga.test.js
- src/redux/material/tests/material.variables.js
- src/redux/model/tests/model.saga.test.js
> Fixed test for comments

- src/pages/order-item/tabs/delivery-details/nova-post/nova-post.js
Added ability to edit any field in nova post form when we edit order
Before
After (2 fields are enabled)
> Refactored novaPost form

- src/pages/email-questions/email-questions-list.js
> refactored pagination

- src/components/forms/model-form/model-form.js
- src/redux/categories/categories.operations.js
- src/redux/model/model.operations.js
Fixed reset cache on model form and also fixed propTypes of categories
> fixed resetCache and proptypes of categories

- src/redux/categories/categories.operations.js
hotfix on categories update cache
> hotfix categories

- src/redux/business-pages/business-pages.operations.js
- src/redux/comments/comments.operations.js
- src/redux/contact/contact.operations.js
- src/redux/header/header.operations.js
- src/redux/home-page-slides/home-page-slides.operations.js
- src/redux/home/home.operations.js
- src/redux/material/material.operations.js
- src/redux/sizes/sizes.operations.js
The store doesn't reset while query in flight anymore Closes #622
> Fixed appearing error message

- src/configs/form-regexp.js
> Fixed regEx for Quill WYSIWYG editor field #704

- src/components/forms/language-panel/language-panel.js
- src/components/forms/news-form/news-form.js
> Save button is active when main fields are filled

- .eslintrc
> fix linter

- src/pages/categories/category-delete/test/category-delete.test.js
- src/pages/categories/category-delete/test/store.js
I wrote an enzyme test on the CategoryDelete page on the admin panel
All test passed
- [✔] 🔽 My branch is up-to-date with "development" branch
- [✔] ✅ All tests passed locally
- [✔] ✨ My changes working with up-to-date front-end and back-end part locally, like a charm
- [✔] 🔗 Link pull request to issue
> component test

- src/components/nav-menu/tests/nav-menu.test.js
- src/components/nav-menu/tests/variables.js
Created enzyme tests for navMenu component
> Enzyme test for navMenu

- src/components/comments-section/comments-section.js
- src/components/comments-section/comments-section.style.js
- src/components/forms/product-form/product-form.js
- src/components/forms/product-form/product-form.styles.js
- src/redux/comments/comments.operations.js
> Fixed show comments issue

- package-lock.json
- package.json
- src/components/create-color/tests/create-color.test.js
Wrote test for CreateColor component
> Added test for CreateColor component Test/428

- src/components/forms/news-form/news-form.js
- src/configs/index.js
- src/configs/news-form-helpers.js
- src/utils/use-news-handlers.js
Changed the photo upload handlers in News form. It has resolved the issue with 513 Payload Too Large.
> refactored photo upload

- src/components/buttons/save-button/save-button.js
- src/components/forms/material-form/material-form.js
Fixed initial values on update material form.
Original             
Updated
> fixed initial values

- src/components/create-color/tests/create-color.test.js
- src/components/create-color/tests/mockStore.js
- src/components/create-color/tests/mockstore.js
-refactored test
-removed magic strings
-added a test case
> refactored test, removed magic strings, added a test case

- src/components/filter-search-sort/filter-by-multiple-values/filter-by-multiple-values.styles.js
Make badge icon round
Changed '& span' to ''&>span''.
> fix: make badge icon round

- src/components/buttons/back-button/back-button.js
- src/components/forms/category-form/category-form.js
- src/pages/history/history-details/history-details.js
- src/pages/order-item/order-item.js
- src/pages/users/users-details/users-details.js
Fixed BackButton route for CategoryForm and added new routes for HistoryDetails, OrderItem and UserDetails.
> Fixed BackButton routes Hotfix/779

- src/pages/history/history-details/history-details.js
- src/pages/history/history-details/history-details.styles.js
- src/pages/history/history.styles.js
Fixed all mentioned bugs with style, also I have found some strange table styling when in night mode and also restyled it to be at least comprehensible
> fixed styling

- src/configs/table-head-row-titles.js
- src/pages/comments/comment-edit/comment-edit.styles.js
- src/pages/main-page/main-page.js
- src/pages/main-page/main-page.styles.js
- src/pages/main-page/tests/main-page.test.js
- src/pages/main-page/tests/variables.js
- src/pages/pattern/tests/__snapshots__/pattern-page.test.js.snap
- src/redux/comments/comments.operations.js
- src/utils/comment.js
Add style and route to recent comments
Fix delete method
> Style and route in recent comments Feature/849

- src/components/forms/model-form/model-form.js
> solved issue with models page

- src/components/forms/language-panel/tests/language-panel.test.js
- src/components/forms/language-panel/tests/language-panel.variables.js
Add some tests to LanguagePanel.
- [+] 🔽 My branch is up-to-date with "development" branch
- [+] ✅ All tests passed locally
- [+] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [+] 🔗 Link pull request to issue
> (SP:3) Write enzyme test for LanguagePanel component #446

- src/components/forms/news-form/tests/news-form.test.js
- src/components/forms/news-form/tests/news-form.variables.js
Create news-form.test.js with tests
Create news-form.variables.js with mocked variables
- [+] 🔽 My branch is up-to-date with "development" branch
- [+] ✅ All tests passed locally
- [+] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [+] 🔗 Link pull request to issue
> (SP: 5)Write enzyme test for NewsForm component #449

- src/components/forms/pockets-form/pockets-form.js
- src/components/forms/pockets-form/pockets-form.styles.js
- src/utils/pockets-form.js
> fix styles pockets-form

- src/redux/pattern/pattern.operations.js
- src/utils/pattern-form.js
- src/utils/use-pattern-handlers.js
fixed editing and creating new patterns
> fixed editing and adding new patterns

- package-lock.json
- package.json
- src/components/forms/back-form/back-form.js
- src/components/forms/category-form/category-form.js
- src/components/forms/category-form/tests/category-form.test.js
- src/components/forms/category-form/tests/category-form.variables.js
- src/components/forms/constructor-form/constructor-form.js
- src/components/forms/contacts-form/contacts-form.js
- src/components/forms/home-page-slide-form/home-page-slide-form.js
- src/components/forms/model-form/model-form.js
- src/components/forms/news-form/news-form.js
- src/components/forms/pattern-form/pattern-form.js
- src/components/forms/pockets-form/pockets-form.js
- src/containers/image-upload-container/image-upload-container.js
- src/containers/image-upload-container/image-upload-previewContainer.js
- src/containers/image-upload-container/image-upload-previewContainer.styles.js
- src/hooks/product/use-product-addimages.js
- src/pages/home-page/home-page.js
- src/utils/contacts-form.js
- src/utils/pattern-form.js
now to upload a picture, you need just to drag it on the picture zone, instead of always clicking on the needed zones 
(by the way this feature was provided as well)
> added dropping pics fuctionality Feature/897

- src/pages/categories/categories-add/categories-add.js
- src/pages/categories/categories.js
- src/redux/categories/categories.reducer.js
- src/redux/selectors/category.selectors.js
fixed issues with pagination on category page
> fix pagination bugFix/884

- src/components/forms/back-form/back-form.js
- src/pages/home-page-slides/slides-order/slides-order.js
> removed console.logs

- .github/workflows/main.yml
> Add eslint to ci

- README.md
> upload photo and git repo

- src/components/forms/home-page-slide-form/home-page-slide-form.styles.js
> Bugfix/881 Responsive design for Slider form 

- src/index.css
> Change button style when hower on it #847

- src/components/forms/back-form/back-form.js
- src/components/forms/closures-form/closures-form.js
- src/configs/error-messages.js
fixed onblur error messages on back and closures form
> fixed onblur error messages

- src/components/forms/category-form/category-form.js
- src/components/forms/model-form/model-form.js
unique upload photo on model and category page
> unique upload photo on model and category pages

- src/hooks/filters/use-question-filters.js
- src/pages/email-questions/email-questions-list.js
- src/pages/email-questions/tests/email-questions-list.test.js
Fixed codesmell fith filter name
> Fix code smells/use questrion filter

- src/pages/order-item/order-item.js
- src/pages/order-item/tabs/recipient.js
- src/pages/orders/orders-page.js
- src/redux/orders/orders.operations.js
- src/utils/order.js
- src/validations/orders/order-form-validation.js
Update orders method after order migration in admin
> Update orders method after order migration in admin

- src/configs/form-regexp.js
> delete unused regex row bugfix/937

- src/components/forms/pockets-form/tests/mockPockets.js
- src/components/forms/pockets-form/tests/pockets-form.test.js
> Enzyme tests for pocket forms 

- src/redux/history/history.sagas.js
- src/redux/history/test/history.actions.test.js
- src/redux/history/test/history.reducer.test.js
- src/redux/history/test/history.sagas.test.js
- src/redux/history/test/history.variables.js
Adds tests for files history.actions.js and history.reducer.js
- [+] 🔽 My branch is up-to-date with "development" branch
- [+] ✅ All tests passed locally
- [+] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [+] 🔗 Link pull request to issue
> add tests for files historyAAction and historyReducer

- src/components/forms/comment-form/comment-form.js
- src/components/forms/product-form/product-form.js
- src/pages/order-item/order-item.js
Add custom confirmation modal  when there are unsave changes in Orders, Products, Comments, and admin click Back button.
> (SP:2)Add confirmation modal in Back button #950

- src/components/forms/pattern-form/pattern-form.js
- src/redux/pattern/pattern.operations.js
- src/utils/pattern-form.js
> fixed pattern model

- src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
- src/components/forms/business-page-form/tests/business-page-form.test.js
- src/components/forms/business-page-form/tests/business-page-form.variables.js
440/tests Writed tests for business-page-form
> 440/tests Writed tests for business-page-form

- src/components/forms/header-form/tests/header-form.test.js
- src/components/forms/header-form/tests/header-form.variables.js
983/tests Writed enzyme tests for header-form component
> 983/tests Writed enzyme tests for header-form component

- src/containers/product-materials-container/product-materials-container.js
- src/containers/product-species-container/product-species-container.js
now fields without content are disabled
> added disable if no content

- src/components/forms/reply-comment-form/reply-comment-form.js
Add validation to reply commen
> validation reply comment

- src/components/buttons/save-button/__snapshots__/save-button.test.js.snap
- src/components/buttons/save-button/save-button.js
- src/components/buttons/save-button/save-button.test.js
- src/components/forms/back-form/back-form.js
- src/components/forms/basics-form/basics-form.js
- src/components/forms/bottom-form/bottom-form.js
- src/components/forms/business-page-form/business-page-form.js
- src/components/forms/category-form/category-form.js
- src/components/forms/closures-form/closures-form.js
- src/components/forms/comment-form/comment-form.js
- src/components/forms/constructor-form/constructor-form.js
- src/components/forms/contacts-form/contacts-form.js
- src/components/forms/header-form/header-form.js
- src/components/forms/home-page-slide-form/home-page-slide-form.js
- src/components/forms/material-form/material-form.js
- src/components/forms/model-form/model-form.js
- src/components/forms/news-form/news-form.js
- src/components/forms/pattern-form/pattern-form.js
- src/components/forms/pockets-form/pockets-form.js
- src/components/forms/position-form/position-form.js
- src/components/forms/product-form/product-form.js
- src/components/forms/reply-comment-form/reply-comment-form.js
- src/components/forms/size-form/size-form.js
- src/components/forms/straps-form/straps-form.js
- src/components/forms/tests/bottom/bottoms-form.test.js
- src/hooks/form-dialog/use-unsaved-changes-handler.js
- src/pages/comments/comment-edit/tests/__snapshots__/comment-edit.test.js.snap
Refactored use-unsaved-changes-handler hook
> Refactored use-unsaved-changes-handler hook

- src/components/color-circle/tests/color-circle.test.js
- src/components/color-circle/tests/color-circle.variables.js
Written enzyme tests for ColorCircle component
> 970/tests Tests for ColorCircle

- src/configs/error-messages.js
> fixed proposition messages

- src/components/forms/back-form/back-form.js
- src/components/forms/basics-form/basics-form.js
- src/components/forms/basics-form/basics-form.styles.js
- src/components/forms/basics-form/tests/basics-form.test.js
- src/components/forms/common.styles.js
- src/components/forms/tests/back/backs-form.test.js
- src/configs/labels.js
- src/configs/titles.js
- src/containers/additional-price-container/additional-price-container.js
- src/containers/additional-price-container/additional-price-container.styles.js
- src/containers/additional-price-container/index.js
- src/pages/back/back-page.js
- src/pages/basics/basics-page.js
- src/redux/back/back.operations.js
- src/redux/basics/basics.operations.js
- src/redux/root.saga.js
- src/utils/back-form.js
- src/utils/basics-form.js
- src/utils/use-back-handlers.js
- src/utils/use-basics-handlers.js
Fixed additional price for basic and back. Also created a new component additional price for future refactoring of forms. That component can be used for full additional price (with Absolute and Relative prices) or part (only Absolute value).
This branch must be ran with this branch https://github.com/ita-social-projects/horondi_client_be/pull/862.
| ** ![image](https://user-images.githubusercontent.com/50678261/134084804-7f79f999-8433-453e-910f-3c8bc955eb61.png)** | ** ![image](https://user-images.githubusercontent.com/50678261/134084748-8e7e6a41-3562-43c3-952b-00a0b2da77e7.png)** |
> Fix Currency for Basic and Back On Admin #997

- src/components/forms/business-page-form/business-page-form.js
- src/components/forms/header-form/header-form.js
- src/configs/error-messages.js
- src/configs/form-regexp.js
Added validation to business page and headers
> add validation to business page and headers

- src/components/forms/product-form/product-form.js
- src/pages/products/product-add/products-add.js
now we can reload add-products page without errors
> fixed none materials

- src/pages/model/constructor/constructor-page/constructor-page.js
- src/pages/order-item/tabs/add-product-form/add-product-form.js
- src/pages/order-item/tabs/edit-product-form/edit-product-form.js
- src/pages/order-item/tabs/products.js
- src/redux/orders/orders.operations.js
- src/utils/order.js
There was fixed error with order creating
Error occurs when website was trying to load products' prices
> fixed orders error

- src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
- src/components/forms/material-form/material-form.js
- src/configs/labels.js
- src/configs/orders.js
- src/pages/comments/comment-edit/tests/__snapshots__/comment-edit.test.js.snap
- src/pages/model/constructor/constructor-page/constructor-page.js
- src/pages/order-item/order-item.js
- src/pages/order-item/order-item.styles.js
- src/pages/order-item/tabs/index.js
- src/pages/order-item/tabs/registered-user.js
- src/pages/order-item/tabs/tests/registered-user-tests/registered-user.test.js
- src/pages/order-item/tabs/tests/registered-user-tests/registered-user.variables.js
- src/redux/orders/orders.operations.js
- src/utils/order.js
Add new tab to orders "Registered user" 
Link for backend pull request https://github.com/ita-social-projects/horondi_client_be/pull/851
> choose register user on order history #882

- src/components/forms/back-form/back-form.js
- src/components/forms/bottom-form/bottom-form.js
- src/components/forms/pattern-form/pattern-form.js
- src/configs/form-regexp.js
- src/pages/order-item/tabs/registered-user.js
Fix bug with selecting registered user in order
> Fix bug with selecting registered user in order

- src/components/dialog-window/tests/__snapshots__/dialog-window.test.js.snap
- src/components/dialog-window/tests/dialog-window.test.js
- src/components/dialog-window/tests/dialog-window.variables.js
431/tests Enzyme tests for DialogWindow component
> 431/tests Enzyme tests for DialogWindow component

- src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
- src/components/forms/size-form/size-form.js
- src/components/forms/size-form/size-form.styles.js
- src/components/tooltip/index.js
- src/components/tooltip/tests/tooltip.test.js
- src/components/tooltip/tests/variables.js
- src/components/tooltip/tooltip.js
- src/components/tooltip/tooltip.styles.js
- src/configs/tooltip-titles.js
> Hint buttons

- src/components/container-filters/tests/container-filters.test.js
- src/components/filters-components/filter-clear/component-filter-clear.js
- src/components/filters-components/filter-clear/index.js
- src/components/filters-components/filter-date-range-picker/component-filter-date-range-picker.js
- src/components/filters-components/filter-date-range-picker/index.js
- src/components/filters-components/filter-multiple-picker/component-filter-multiple-picker.js
- src/components/filters-components/filter-multiple-picker/index.js
- src/components/filters-components/filter-radio-picker/component-filter-radio-picker.js
- src/components/filters-components/filter-radio-picker/index.js
- src/components/filters-components/filter-search/component-filter-search.js
- src/components/filters-components/filter-search/index.js
- src/components/filters-components/filter-single-picker/component-filter-single-picker.js
- src/components/filters-components/filter-single-picker/index.js
- src/components/filters-components/tests/filters-components.test.js
- src/components/forms/business-page-form/tests/__snapshots__/business-page-form.test.js.snap
- src/pages/orders/components/tests/filters.test.js
- src/pages/orders/filters/filters.js
- src/pages/orders/orders-page.js
Refactoring filters for admin page orders
> Refactor filters for orders

- src/configs/messages.js
bugFix/1027 Edited label no orders
> bugFix/1027 Edited label no orders

- src/pages/news/tests/__snapshots__/news.test.js.snap
- src/pages/news/tests/news-page.test.js
- src/pages/news/tests/newsList.js
512/tests Writed enzyme tests for news page
> 512/tests Writed enzyme tests for news page

- cypress/integration/headers-page/headers-page.test.js
- cypress/integration/headers-page/headers-page.variables.js
- cypress/support/commands.js
tests/379/ Added e2e tests for headers page
> tests/379/ Added e2e tests for headers page

- src/utils/format-phone-number.js
Fixed phone number
bugfix/1052/phone-number
> fixed phone number

- src/components/dialog-window/dialog-window.js
- src/components/dialog-window/dialog-window.styles.js
Wrote styles for 'Yes' button.
| ** original screenshot **  
| ** updated screenshot **  
|
> Spread out buttons in confirmation modal

- src/validations/models/model-form-validation.js
Add validation to UA name of the model.
| ![Screenshot_67](https://user-images.githubusercontent.com/67831961/135496948-c4fbab08-7f23-4cac-9f9f-fa6759d05ec1.png) |![Screenshot_68](https://user-images.githubusercontent.com/67831961/135497009-89e9ef62-fcd3-468e-bd40-fb189f53f761.png) |
> add validation

- src/components/forms/contacts-form/contacts-form.js
> Added map api key

- src/components/buttons/delete-button/delete-button.test.js
- src/components/buttons/save-button/save-button.test.js
- src/components/buttons/standard-button/standard-button.test.js
Fixed codesmells in admin buttons tests
> Fixed codesmells in admin buttons tests

- src/components/buttons/save-button/save-button.js
- src/components/filters-components/filter-radio-picker/component-filter-radio-picker.js
- src/components/filters-components/filter-single-picker/component-filter-single-picker.js
- src/components/forms/user-form/user-form.js
- src/components/icons/customized-edit-icon/edit-button.test.js
- src/configs/labels.js
- src/containers/image-upload-container/image-upload-container.js
- src/pages/users/user/user-details/user-details.js
Fixed codesmells and console errors in user-form component
> Hotfix/1115/codesmells and console errors in user-form component

- src/configs/menu-categories.js
Fixed routes in business pages
> Fixed routes in business pages

- src/components/forms/news-form/news-form.js
Remove validations from news updating
> Remove validations from news updating form in Admin

- src/components/nav-menu/nav-menu.js
We had a problem with the navigation bar, it didn't work properly. When we open the popup of several sections, they remain open, as shown in the screenshot. But when we open the popup menu of the new section, we need to close the previous one.
| **
> fix navbar on admin

- src/configs/form-regexp.js
- src/pages/home-page/tests/home-page.test.js
- src/pages/orders/filters/filters.js
According to task I fixed all code smells in files:
form-regexp.js Simplify regular expression to less than 20 symbols (fields: onlyPositiveFloat, phoneNumber);
home-page.test.js Correct assertion rule "Component should exist"
- [ X ] 🔽 My branch is up-to-date with "development" branch
- [ X ] ✅ All tests passed locally
- [ X ] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [ X ] 🔗 Link pull request to issue
> Check and fix all code smells

- src/containers/additional-price-container/additional-price-container.styles.js
Fixed error margin and color from black to red in pocket constructor.
| ** ![зображення](https://user-images.githubusercontent.com/56231198/159091717-a257e587-b849-4df2-9fa2-44155e59e3bb.png)** | ** ![зображення](https://user-images.githubusercontent.com/56231198/159329734-5e8db581-50ea-490c-883e-1da4be0cf9c8.png)** |
> fixed error text color

- src/pages/straps/straps-page.js
Made to photo of the straps displayed
| ** ![зображення](https://user-images.githubusercontent.com/56231198/160098165-c0543d00-79f6-41cc-a1cf-cea66e67fb03.png)** | ** ![зображення](https://user-images.githubusercontent.com/56231198/160098045-c44c45c6-86c8-487c-b932-8a9f634cfa04.png)** |
> fixed displayed photo of the straps

- src/configs/table-head-row-titles.js
| ![before](https://user-images.githubusercontent.com/100776036/160276357-612e61f2-973b-46ed-a343-ebabc69b1afc.png) | ![after](https://user-images.githubusercontent.com/100776036/160276364-0c1f54a3-c2bb-419c-a3b4-f8459a1f38eb.png) |
> Fix columns naming according to their appointment

- src/redux/products/products.operations.js
Fixed bug with deleting product
| 
| ![image](https://user-images.githubusercontent.com/84774115/159799052-f098d793-c197-4588-9d4d-cf7f8a7edd62.png) |
> Fix bug: delete product error

- src/hooks/deleteValidation/useDeleteValidation.js
Fixed error of deleting material
| ![image](https://user-images.githubusercontent.com/84774115/160291960-8045feb6-8c42-4e96-a182-fbaa700e3874.png) | ![image](https://user-images.githubusercontent.com/84774115/160291978-dd8ddc95-a12e-42d6-b938-9e61ec33cd1f.png) |
> material delete validation

- src/redux/pattern/pattern.operations.js
Handle error message from back when get response from updatePattern mutation
| ![image](https://user-images.githubusercontent.com/84774115/161286496-775e89f1-7575-41e0-9678-90ef9e92a0af.png) |![image](https://user-images.githubusercontent.com/84774115/161286522-2d1a4846-41fd-4c7c-8e07-f2aeec7daea0.png) |
> handle custom backend error

- src/configs/index.js
There was bad UserRoles config for use-user-tabs hook
| ** ![image](https://user-images.githubusercontent.com/45914032/161050606-1e62d79a-ae24-4501-a2f8-8bf858aa9bb5.png) ** | ** ![image](https://user-images.githubusercontent.com/45914032/161050639-0c17f13c-5650-44f0-b68e-a7398972cb23.png) ** |
> fixed UserRole config

- src/pages/users/components/user-tab/user-tab.js
- src/redux/users/users.operations.js
Fix problem with avatar, which not displayed in the general users list.
| ** ![зображення](https://user-images.githubusercontent.com/56231198/161624174-bc67e89a-0a31-4eb8-8802-0f1d421c0aec.png)** | ** ![зображення](https://user-images.githubusercontent.com/56231198/161624023-5c73e665-097c-4f50-8f0c-b20710a8a3b0.png)** |
> fix avatar on user tab list

- src/pages/back/back-page.js
- src/pages/closures/closures-page.js
- src/pages/straps/straps-page.js
- src/redux/back/back.operations.js
- src/redux/closures/closures.operations.js
- src/redux/straps/straps.operations.js
- src/utils/back-form.js
- src/utils/closures-form.js
- src/utils/material-form.js
- src/utils/pattern-form.js
- src/utils/size-helpers.js
- src/utils/straps-form.js
> refactor back, straps, closures

- src/pages/certificates/certificates-page.js
Fix bug with certificates displayed
> Fix bug with certificates displayed

- src/components/forms/product-form/product-form.js
- src/components/forms/product-form/tests/product-form.spec.js
- src/configs/error-messages.js
- src/containers/product-info-container/product-info-container.js
- src/containers/product-species-container/product-species-container.js
- src/hooks/product/use-product-validation.js
- src/pages/products/product-add/product-add-images/product-add-images.js
Adding product without a photo is not allowed now.
> fixed bug with allowing add product without a photo an some other fixes

- src/configs/form-regexp.js
Update regular expression in Pattern Page
| ** ![зображення](https://user-images.githubusercontent.com/56231198/162633566-20c01a8f-4cb3-4f24-aa1f-44c07f69b729.png) ** | ** ![зображення](https://user-images.githubusercontent.com/56231198/162633513-ff265f94-30f1-4fea-982b-c0133fc3cf8f.png) ** |
> fixed regexp

- src/pages/home-page-slides/slides-order/slides-order.js
Description and title fields have not been passed. It needs for createTranslations() handler at backend
> pass fields for tranlations_keys

- src/configs/error-modal-messages.js
- src/pages/users/components/admin-tab/admin-tab.js
- src/pages/users/components/admin-tab/tests/admin-page.test.js
- src/pages/users/components/admin-tab/tests/variables.js
- src/pages/users/components/user-tab/tests/user-page.test.js
- src/pages/users/components/user-tab/tests/variables.js
- src/pages/users/components/user-tab/user-tab.js
- src/pages/users/components/users-filters/UsersFilters.js
Remove table with users when on users page and admins page
| ![before user](https://user-images.githubusercontent.com/100776036/162719371-70292fd9-9a8e-486b-89fd-9f890e03dc23.png) | ![after user](https://user-images.githubusercontent.com/100776036/162719453-04d0a94a-0107-4e1e-bc96-58b3adb2df7d.png) 
| ![admin before](https://user-images.githubusercontent.com/100776036/162720167-3c39c296-3dd5-474b-a8b0-c8e3f420a269.png) | ![admins eroor](https://user-images.githubusercontent.com/100776036/162719807-bccea151-eb0c-4812-9915-4358c33b2d52.png)
> [Users] Remove table with products when on users page

- src/pages/certificates/checkBoxes/checkBoxes.js
Added a limit counts of certificates that can be generated to 10
| ** <img width="622" alt="зображення" src="https://user-images.githubusercontent.com/56231198/163061142-84037ad8-9ca9-4795-b428-e05170263867.png"> ** | ** <img width="616" alt="зображення" src="https://user-images.githubusercontent.com/56231198/163060958-4f463037-fc0a-405e-a1ab-2003dccd4137.png"> ** |
> add limit counts

- src/components/forms/home-page-slide-form/home-page-slide-form.js
- src/configs/form-regexp.js
Reg exp and error message for uk title input fixed
> error message fixed

- package-lock.json
- package.json
- src/configs/messages.js
- src/configs/titles.js
- src/pages/certificates/certificates-page.js
- src/pages/certificates/hooks/use-certificates.js
- src/pages/certificates/operations/certificate.mutation.js
- src/pages/certificates/tests/certificates-page.spec.js
- src/pages/certificates/tests/certificates-page.variables.js
- src/pages/certificates/tests/use-certificates.spec.js
- src/redux/dialog-window/dialog-window.reducer.js
- src/utils/use-success-snackbar.js
Add posibilities to delete certificates and update their status.
> Delete and update certificates

- src/configs/orders.js
- src/pages/promo-code/operations/categories-list.queries.js
- src/pages/promo-code/promo-code-add/tests/promo-code-add.spec.js
- src/pages/promo-code/promo-code-edit/test/promo-code-edit.spec.js
- src/pages/promo-code/promo-code-edit/test/promo-code-edit.variables.js
- src/pages/promo-code/promo-code-form/promo-code-form.js
- src/pages/promo-code/promo-code-form/test/promo-code-form.spec.js
- src/pages/promo-code/promo-code-form/test/promo-code-form.variables.js
Checkboxes list in promo-code-form now is getting from query instead of hardcoded list.
| ** ![image](https://user-images.githubusercontent.com/45914032/166104808-029090a1-e01c-4e6b-bffa-4c544a265513.png) ** | ** ![image](https://user-images.githubusercontent.com/45914032/166104988-847b1b32-7eb2-46e5-8785-b8514a30a1ee.png) ** |
> refactored  categories-list for checkboxes

- src/configs/filter-labels.js
- src/consts/certificate-status.js
- src/consts/promo-code-status.js
- src/hooks/filters/use-certificate-filters.js
- src/hooks/filters/use-certificate-filters.test.js
- src/hooks/filters/use-promo-code-filters.js
- src/hooks/filters/use-promoCode-Certificate-filters.js
- src/pages/certificates/certificates-page.js
- src/pages/certificates/hooks/use-certificates.js
- src/pages/certificates/operations/certificate.queries.js
- src/pages/certificates/tests/certificates-page.spec.js
- src/pages/certificates/tests/certificates-page.variables.js
- src/pages/promo-code/operations/promo-code.queries.js
- src/pages/promo-code/promo-code-page.js
- src/utils/certificate.js
- src/utils/promo-code.js
Fixed bug pagination in Certificate, created sorting for Certificates and Promo-code
> Create component for sorting and filtering PromoCodes and Certificates 

- src/configs/error-messages.js
- src/utils/format-phone-number.js
| ![before number](https://user-images.githubusercontent.com/100776036/166451834-20e0e3db-3450-47b0-9752-569b8874efd8.png) | ![after number](https://user-images.githubusercontent.com/100776036/166451858-f848269c-e8d0-4adb-8a45-61116da16c6b.png) |
> Fix phone number format

- src/components/forms/back-form/back-form.js
- src/components/forms/basics-form/basics-form.js
- src/components/forms/bottom-form/bottom-form.js
- src/components/forms/closures-form/closures-form.js
- src/components/forms/comment-form/comment-form.js
- src/components/forms/contacts-form/contacts-form.js
- src/components/forms/home-page-slide-form/home-page-slide-form.js
- src/components/forms/material-form/material-form.js
- src/components/forms/model-form/model-form.js
- src/components/forms/news-form/news-form.js
- src/components/forms/pattern-form/pattern-form.js
- src/components/forms/pattern-form/tests/pattern-form.spec.js
- src/components/forms/pattern-form/tests/pattern-form.variables.js
- src/components/forms/pockets-form/pockets-form.js
- src/components/forms/position-form/position-form.js
- src/components/forms/position-form/tests/position-form.spec.js
- src/components/forms/position-form/tests/position-form.variables.js
- src/components/forms/size-form/size-form.js
- src/components/forms/straps-form/straps-form.js
> [Contacts] Save button doesn't work properly

- src/components/nav-menu/nav-menu.js
- src/components/nav-menu/nav-menu.styles.js
Changed color of nav-menu icons according to figma layout.
> changed color of nav-menu icons

- src/configs/filter-labels.js
> [Order] Incorrect sorting by order price.

- src/components/icons/customized-edit-icon/customized-edit-icon.js
- src/components/nav-menu/nav-menu.js
- src/containers/table-container-row/table-container-row.js
- src/pages/about-us/tests/about-us.spec.js
- src/pages/promo-code/tests/promo-code-page.spec.js
> Fixed navbar collapsing

- src/utils/handle-orders-page.js
Fixed bug with changing or adding order status other than "Created" or "Confirmed".
> Fixed bug with changing or adding order status

- src/components/nav-menu/nav-menu.js
> fixed nav-menu collapsing

- src/components/filter-search-sort/filter-by-multiple-values/filter-by-multiple-values.styles.js
> Text "Гаманець ...." in sorting gets out of the block

- src/configs/filter-labels.js
> When sorting for answers data, there are fileds with no answers

- src/utils/order.js
When creating ukr post order, data where empty after submit
> correct ukr post submit

- src/configs/menu-categories.js
- src/pages/promo-code/promo-code-page.js
Was added field and removed button
| ![image](https://user-images.githubusercontent.com/80908916/174662645-d3f87cc2-e4f8-4363-a4f7-d2aae4cf6232.png) | ![image](https://user-images.githubusercontent.com/80908916/174662707-a372b276-2b13-4b4d-a7bb-13afcda4069c.png) |
> add_field_create_promocode_to_menu_category-promocodes

- src/configs/error-modal-messages.js
- src/redux/sizes/sizes.operations.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any
> Add validation for checking if size is already created 

- src/components/nav-menu/nav-menu.js
- src/components/nav-menu/nav-menu.styles.js
Added disableGutters property to all list items, added paddings to list items and bage
|![175270856-ceb32ae2-792e-4702-ae19-b410c01c362f](https://user-images.githubusercontent.com/97129041/175528931-1c4d4f42-4f22-431a-9470-1977dac89148.png) |![padding](https://user-images.githubusercontent.com/97129041/175529098-d1e60e45-3b81-4d89-83f2-c348eb03e21f.png)|
> added indent to expanded tabs, refactored code in nav-menu element

- src/components/forms/product-form/product-form.js
- src/hooks/product/use-product-validation.js
added dirty to save button
https://user-images.githubusercontent.com/80908916/176132402-0c9ec886-fb6f-48e7-8c70-be0fac41f39a.mp4
> Product/1374/product image adding/editing is not working

- src/components/nav-menu/nav-menu.js
- src/components/nav-menu/nav-menu.styles.js
Added a badge to indicate questions count when the Clients tab collapsed.
| ![MergedImages](https://user-images.githubusercontent.com/86732805/175906586-a5c42927-b067-47c9-8115-64fd1a88a38c.png) | ![MergedImages (1)](https://user-images.githubusercontent.com/86732805/175906610-8eb4422b-ab71-4758-aca3-8ef09b27922c.png) |
> Duplicate the notification about new clients questions

- src/configs/table-head-row-titles.js
- src/pages/order-item/order-item.js
- src/pages/order-item/tabs/add-product-form/add-product-form.js
- src/pages/order-item/tabs/edit-product-form/edit-product-form.js
- src/pages/order-item/tabs/products.js
- src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.spec.js
- src/pages/order-item/tabs/tests/add-product-form-tests/add-product-form.variables.js
- src/pages/order-item/tabs/tests/edit-product-form-tests/edit-product-form.spec.js
- src/pages/order-item/tabs/tests/edit-product-form-tests/edit-product-form.variables.js
- src/pages/order-item/tabs/tests/products-tests/products.spec.js
- src/pages/order-item/tabs/tests/products-tests/products.variables.js
- src/redux/orders/orders.operations.js
- src/utils/order.js
- src/utils/tests/order.test.js
- src/utils/tests/order.variables.js
| ![before](https://user-images.githubusercontent.com/100776036/176757539-dc569f8b-d8f0-46c3-a61a-5ac63a6fc4fc.png)|  ![afret](https://user-images.githubusercontent.com/100776036/176757568-0e6f1cab-f14e-41ee-b3d3-03a8f9599ebe.png) |
> [Orders] Displayed price without discount within promo code was used

- src/components/buttons/back-button/back-button.js
- src/components/buttons/back-button/back-button.styles.js
- src/components/nav-bar/nav-bar.js
- src/utils/passThemeStatus.js
as to figma, back button  bacome with white text and white border. also as to figma the width of button НАЗАД іs the same as width of ЗБЕРЕГТИ button
Original Screenshot: 
Original Screenshot:
> changed colors of back botton as to figma

- src/consts/history-events.js
- src/pages/material/material-about-details.js
- src/pages/material/tests/material-about-details.spec.js
- src/pages/material/tests/material-about.variables.js
- Added a history record name.
- Fixed rendering of empty form in case of error.
> Add changes in About materials to the Recent changes

- src/pages/certificates/create-certificate/create-certificate.js
When the admin adds a certificate deleted function that was changing the date
> When admin adding certificate wrong date

- src/pages/certificates/hooks/use-certificates.js
- src/pages/certificates/operations/certificate.mutation.js
- src/pages/certificates/tests/certificates-page.variables.js
> refactor updateStatus

- src/configs/button-titles.js
- src/pages/promo-code/promo-code-page.js
- src/pages/promo-code/promo-code-page.styles.js
add create promocode button on proocode page
> add create promo code button

- package-lock.json
- src/pages/certificates/create-certificate/create-certificate.js
- src/pages/certificates/tests/create-certificate.spec.js
Button 'generate' must be disabled if user not enter email and select the price.
Before
After
> email field should be required

- src/configs/regexes.js
- src/validations/orders/order-form-validation.js
[Orders] Fixed phone number validation when you add order.  This validation includes telephone numbers all over the world. 
Before
After
> fixed phone validation when you add order

- src/containers/table-container-collapsable-row/table-container-collapsable-row.js
Fix header in 'email questions' table
> fix table header in email questions table

- src/pages/comments/comments.js
- src/pages/users/components/user-tab/user-tab.js
> Bugfix/1490/1491/fix 'coments' and 'user information' tables 

- src/configs/statuses.js
- src/consts/certificate-status.js
- src/pages/certificates/certificates-page.js
- src/pages/certificates/hooks/use-certificates.js
- src/pages/certificates/operations/certificate.queries.js
- src/pages/certificates/tests/certificates-page.variables.js
- src/pages/certificates/tests/use-certificates.spec.js
Added inProgress to filter and show certificates with inProgress status
|         Updated          |
| :-----------------------: 
|![image](https://user-images.githubusercontent.com/63456632/200869172-b8fd0714-30c0-4645-9768-029a5c596708.png)|
> added inProgress to filter and show certificates with inProgress status

- src/components/autocomplete-options/autocomplete-options.js
- src/pages/constructor-list/constructor-list-page.js
- src/pages/constructor-list/tests/mockStore.js
> refactored constructor

- src/hooks/deleteValidation/useDeleteValidation.js
- src/pages/products/products-page.js
- src/utils/use-success-snackbar.js
fix delete pop-up on materials page
> bugfix/1423/fix delete pop-up

- src/components/nav-bar/nav-bar.styles.js
- src/configs/orders.js
- src/consts/menu-categories.js
- src/containers/table-container-row/table-container-row.js
- src/pages/about-us/about-us.js
- src/pages/certificates/operations/certificate.queries.js
- src/pages/order-item/order-item.js
- src/pages/order-item/tabs/add-product-form/add-product-form.js
- src/pages/order-item/tabs/add-product-form/add-product-form.styles.js
- src/pages/order-item/tabs/products.js
- src/redux/orders/orders.operations.js
- src/utils/order.js
- src/utils/order.values.js
Added list that shows info about promo code or certificate, fixed discounts on products when certificate is used
| ![194302512-14989596-02da-4fe2-b388-5a3e9bb64f1d](https://user-images.githubusercontent.com/97129041/201521138-5e0a8717-a525-4fe1-8d6d-fbcf5f6bfc2e.png)| ![discount](https://user-images.githubusercontent.com/97129041/201521002-ed1f2bc8-1ea6-4db5-91c9-ac1b1a56e8af.png)|
> Added list shows discount information

- src/pages/constructor-list/constructor-list-page.js
List of constructor items should not contain items not available for constructor
| ![image](https://user-images.githubusercontent.com/45914032/204760474-a998bc66-193f-4178-841f-0e7a44fe3933.png) | ![image](https://user-images.githubusercontent.com/45914032/204760534-4f196980-0087-4270-a557-ff0662ba7119.png) |
> filters list of not available constructors

- src/hooks/user/use-users-handlers.js
Fixed incorrect displaying of user address info when there is no data.
> Fixed incorrect address displaying

- src/redux/email-questions/email-questions.sagas.js
Added call handlePendingEmailQuestionsCount for updating amount of questions after deleting question.
> Quantity of questions on sidebar change when question is deleted.

- src/components/forms/comment-form/comment-form.js
- src/components/forms/reply-comment-form/reply-comment-form.js
- src/configs/error-modal-messages.js
- src/pages/certificates/certificates-page.js
- src/pages/certificates/hooks/use-certificates.js
- src/pages/certificates/operations/certificate.mutation.js
fixed error messages in certificate and comments pages and passed admin id for checking user role in backend
> fix errors messages

- src/components/forms/user-form/user-form.js
- src/configs/form-regexp.js
- src/configs/labels.js
Fixed misnames so the form (address details) can work like it's supposed to.
> Fixed address details editing bug

- src/redux/orders/orders.operations.js
Show correct post office in selected city.
| ![photo_2022-12-14_10-04-19](https://user-images.githubusercontent.com/83120263/207541976-ca5d9324-c1f2-47f8-a450-c3a0b957a25f.jpg) | ![photo_2022-12-14_10-03-50](https://user-images.githubusercontent.com/83120263/207542001-c9809de6-eec0-48d4-b78b-2ea539aa270b.jpg) |
> Show correct post office in selected city

- src/pages/certificates/checkBoxes/checkboxes.styles.js
|![image](https://user-images.githubusercontent.com/56231198/207633417-53c3af3f-86a0-4aa1-ac12-3a1164f6b948.png)|![image](https://user-images.githubusercontent.com/56231198/207633320-61b86f55-6625-4ef3-adf8-b7022c07b545.png)|
> Fix number position when number is 10

- src/components/app/app.js
- src/components/create-color/create-color.js
- src/components/forms/constructor-form/constructor-model-form.js
- src/components/forms/home-page-slide-form/home-page-slide-form.js
- src/components/forms/material-form/material-form.js
- src/components/forms/news-form/news-form.js
- src/components/forms/pattern-form/pattern-form.js
- src/components/nav-bar/nav-bar.js
- src/helpers/constructor-item-test/constructor-item-test.js
- src/hooks/deleteValidation/useDeleteValidation.js
- src/hooks/filter/useFilterSearchAndSort.js
- src/hooks/form-dialog/use-unsaved-changes-handler.js
- src/pages/comments/comment-edit/comment-edit.js
- src/pages/contacts-page/contacts-add/tests/contact-add.spec.js
- src/pages/history/history-details/history-details.js
- src/pages/main-page/main-page.js
- src/pages/material/material-page.js
- src/pages/order-item/tabs/add-product-form/add-product-form.styles.js
- src/pages/order-item/tabs/delivery-details/worldwide/worldwide.js
- src/pages/order-item/tabs/edit-product-form/edit-product-form.js
- src/pages/order-item/tabs/registered-user.js
- src/pages/orders/orders-page.js
- src/pages/pattern/pattern-page.js
- src/pages/statistic/statistic-page.js
- src/propTypes/product-containers.js
Fix all console errors and warnings on Admin Page.
> fix console errors and warnings

- src/containers/product-species-container/product-species-container.js
fixed console warnings on product add page
> fix console warnings

- src/components/forms/business-page-form/business-page-form.js
- src/hooks/form-dialog/use-unsaved-changes-handler.js
- src/pages/material/material-page.js
> Fixed error in static pages

- src/hooks/form-dialog/use-unsaved-changes-handler.js
Fixed useUnsavedChangesHandler
> fixed useUnsavedChangesHandler

- src/containers/images-preview-container/images-preview-container.js
- src/containers/images-upload-container/images-upload-container.js
- src/containers/images-upload-container/images-upload-container.styles.js
> fixed product form theme

- src/pages/order-item/tabs/edit-product-form/edit-product-form.js
- src/pages/order-item/tabs/products.js
- src/utils/order.js
> fix constructor in order

- src/containers/materials-with-color-container/materials-with-color-container.js
> fixed mui select warnings

- src/components/create-color/create-color.js
- src/components/create-color/create-color.styles.js
Now color dialog window work correctly
> Color dialog window should work correctly 

- src/components/comments-section/comments-section.js
- src/redux/email-questions/email-questions.sagas.js
Deleted or answered on last question. And result can see on screens.
| ![image](https://user-images.githubusercontent.com/83120263/209656675-c6f6481b-d709-4bff-93a8-a3d0b1dd1fc8.png) | ![image](https://user-images.githubusercontent.com/83120263/209656794-3d467f05-4837-49ea-83ac-50f225b20009.png) |
> Removed the condition

- src/components/forms/user-form/user-form.js
- src/utils/user-form.js
changed default image in edit profile
> changed default image in edit profile
