ita-social-projects/horondi_admin

src/components/app/app-theme/typography.styles.js
src/pages/main-page/main-page.styles.js

src/components/app/app-theme/thypography.styles.js
Changed "fontSize" proprety in "body2" property and add "fontFamily" property.

Fixed. The 'font-family' and 'font-size' changed

---

src/components/forms/category-form/category-form.js

When we enter valid data without the image the button 'Зберегти' is clickable now and warning message is displayed: 'Додайте зображення до категорії' after clicking on 'Зберегти' button

The button 'Зберегти' isn't clickable and error message doesn't appear

---

src/components/filter-search-sort/filter-by-multiple-values/nav-filter-by-values.js
src/components/filter-search-sort/filter-navbar.js
src/components/filter-search-sort/nav-clear-filters/nav-clear-filters.js
src/components/filter-search-sort/nav-search/nav-search.js
src/components/filter-search-sort/nav-sort/nav-sort.js
src/components/forms/language-panel/language-panel.js
src/containers/product-info-container/product-info-container.js
src/containers/product-materials-container/product-materials-container.js
src/containers/product-species-container/product-species-container.js
src/pages/products/product-add/product-add-images/product-add-images.js

Some of the prop types were not defined correctly, which caused warning printed to the console. Furthermore, enzyme tests would not pass with incorrect prop types. therefore it was important to fix them.
closes #834 
- 🔽 My branch is up-to-date with "development" branch
- ✅ All tests passed locally
- ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- 🔗 Link pull request to issue

fix prop types in product form

---

src/components/buttons/save-button/save-button.js
src/components/dialog-window/dialog-window.js
src/components/forms/business-page-form/business-page-form.js
src/components/forms/category-form/category-form.js
src/components/forms/category-form/tests/category-form.test.js
src/components/forms/comment-form/comment-form.js
src/components/forms/constructor-form/constructor-form.js
src/components/forms/contacts-form/contacts-form.js
src/components/forms/header-form/header-form.js
src/components/forms/home-page-slide-form/home-page-slide-form.js
src/components/forms/material-form/material-form.js
src/components/forms/material-form/tests/material-form.test.js
src/components/forms/news-form/news-form.js
src/components/forms/pattern-form/pattern-form.js
src/components/forms/size-form/size-form.js
src/pages/pattern/tests/__snapshots__/pattern-page.test.js.snap
src/redux/categories/categories.sagas.js
src/redux/contact/contact.reducer.js
src/redux/header/header.sagas.js

Fixed the order of how updating and creating objects to the database works. Previously, the modal window was incorrectly opened at the time object was being added to the database while asking the permission that didn't really matter, as it didn't affect anything, because an object was added anyway. Now it works completely different, because modal shows up before objects are added or updated in the database, so now it acts as intended with a logical approach to user experience.
As we can see it only either updated or creates objects after asking the permission of the user if it was the desired action. 
Also, it is worth noticing that I changed the placement of buttons on the modal, because previously …

Bug fix/848 2

---

src/hooks/filters/use-product-filters.js
src/redux/products/products.operations.js
src/utils/product.js

fixed bug with independent filters, now, when you choose the specific filter in category,  all models are filtered respectively to the available models in this category and vice versa

fixed bug with products by adding dependent inputs

---

src/components/forms/product-form/product-form.styles.js

Fixed bug with a wrong buttons margin on phone version

bug fixed / Responsive design for Product form#872

---

src/components/forms/model-form/model-form.styles.js

Fixed media query for model-form buttonContainer when width smaller than 405px

fixed model form button responsive

---

src/components/create-color/create-color.js
src/configs/error-messages.js

#981 
Added: 
- the button "Створити колір" is not active until we create color
- onBlur with hints
- validations

Fixed create color on materials page

---

src/components/filter-search-sort/filter-by-date/filter-by-date.styles.js
src/components/nav-bar/nav-bar.js

Created a custom styles for DateRangePicker component classes when switching theme.
| ** ![image](https://user-images.githubusercontent.com/39667486/135456680-00c2badc-6203-4ce7-8878-38e17955ca7c.png) ** | ** ![image](https://user-images.githubusercontent.com/39667486/135456242-62a10e70-51b3-42b7-b18c-5fc380ae447f.png)** |

Fixed styles when switching to dark theme

---

src/components/forms/constructor-form/constructor-list-accordion/constructor-list-accordion.js

Go to the constructor tab. List of constructors. Select edit rolltop. Go to the patterns tab. The maximum number of patterns displayed was 10. Now - 20.

increasing the number of patterns

---

src/configs/titles.js
src/pages/certificates/certificatesTable/certificateTable.js
src/pages/certificates/create-certificate/create-certificate.js
src/pages/certificates/operations/certificate.mutation.js
src/pages/certificates/tests/create-certificate.spec.js
src/pages/certificates/tests/create-certificate.variables.js

https://github.com/ita-social-projects/horondi_admin/issues/1189

Admin: generate certificates button invokes mutation

---

src/configs/form-regexp.js

Updated uaNameCreation regexp to be able to rewrite 'Рожево голубий' pattern to 'Рожево-Голубий' in admin.
| ![Clip2net_220317173806](https://user-images.githubusercontent.com/49586997/158839468-ba26df4a-cd25-4188-8a7e-f0e2fd58e57c.png) | ![Clip2net_220317173902](https://user-images.githubusercontent.com/49586997/158839684-4c261b57-ead7-44f2-8f66-b2efcb9451f9.png) |

fix uaNameCreation regexp to properly write color pattern

---

src/components/buttons/save-button/save-button.js
src/components/forms/back-form/back-form.js
src/components/forms/basics-form/basics-form.js
src/components/forms/bottom-form/bottom-form.js
src/components/forms/category-form/category-form.js
src/components/forms/comment-form/comment-form.js
src/components/forms/contacts-form/contacts-form.js
src/components/forms/header-form/header-form.js
src/components/forms/home-page-slide-form/home-page-slide-form.js
src/components/forms/material-form/material-form.js
src/components/forms/model-form/model-form.js
src/components/forms/model-form/tests/model-form.spec.js
src/components/forms/news-form/news-form.js
src/components/forms/news-form/tests/news-form.test.js
src/components/forms/pattern-form/pattern-form.js
src/components/forms/pockets-form/pockets-form.js
src/components/forms/position-form/position-form.js
src/components/forms/reply-comment-form/reply-comment-form.js
src/components/forms/size-form/size-form.js
src/components/forms/straps-form/straps-form.js
src/components/forms/user-form/user-form.js
src/containers/additional-price-container/additional-price-container.js
src/hooks/forms/use-changed-values-checker.js
src/utils/additionalPrice-helper.js

1. Added  type 'number' to price input (in components where it was not)  to prevent entering letters.
2. The field of the corresponding price in hryvnias no longer shows negative values or 'NaN'.
3. The 'save-button' disabled state now working right .
4. Now we use 'useChangedValuesChecker' (custom hook) inside the save-button and not in every component where this button is used.
| ![image](https://user-images.githubusercontent.com/59802802/160696794-9e082f11-a978-47aa-a16f-3fb354b7bf3b.png)

Bugfix/1261/fix price input  and save-button behaviors

---

src/configs/regexes.js

Save button was disabled even when changes were made. The reason for this was a difference in regular expressions that were used on admin part and on backend. From backend was fetched  phoneNumber, which didn't pass the regular expression that was made on a admin part, and as a result - save button remained disabled.(because it thougth that there is an error in user editing, but it actually a phoneNumber that came from db that didn't pass the validation)
| ![image](https://user-images.githubusercontent.com/84774115/161832702-83bb3706-a287-4b01-9a63-bcece676b446.png) |![image](https://user-images.githubusercontent.com/84774115/161832761-0889050c-2162-4380-b292-aa0685ee052c.png) …

save button works

---

src/configs/index.js
src/configs/titles.js
src/pages/statistic/statistic-doughnut/legends-list/legends-list.js

1. Added statistics labels , colors .
2. Fixed bug which arose because of the same values of key property in statistic items.
| ![image](https://user-images.githubusercontent.com/59802802/161812352-681ffdf7-292e-430c-8c8b-9b84d27f536e.png) | ![image](https://user-images.githubusercontent.com/59802802/161811914-41436293-f2b9-4310-afe9-67d982706640.png) |
Items with the same key.

Fixed undefined-data, unique keys and colors in StatisticDoughnut

---

src/configs/orders.js
src/pages/promo-code/promo-code-page.js
src/pages/promo-code/tests/promo-code-page.variables.js

Promocode had only two statuses: active and expired. However, if promocode had start date after current date(now) there was no correspondent status to it. I fixed that, adding 'Planned' status to promocodes
Original
Updated

added status 'Planned' to promocodes

---

src/configs/error-messages.js
src/configs/form-regexp.js
src/validations/promo-code/promo-code-validation.js

Added validation must have a positive number and a multiple of 5

Wrong input validation on promocode creation.

---

src/redux/material/material.sagas.js

[Catalog] Size, Gobelens list appears only after page reload

---

src/pages/order-item/tabs/delivery-details/worldwide/worldwide.js

State/province is not required. And when it comes empty from db, now fields lower are not changing.
| ![Clip2net_220520094514](https://user-images.githubusercontent.com/49586997/169469318-eb3d1b47-9506-4092-b86e-3dc0f7004ef1.png) | ![Clip2net_220520094554](https://user-images.githubusercontent.com/49586997/169469384-fe4ee7c7-fb13-434b-8599-99d1117330df.png) |

remove setFieldValue in worldwide useEffect

---

src/pages/promo-code/promo-code-edit/test/promo-code-edit.spec.js
src/pages/promo-code/promo-code-form/promo-code-form.js
src/pages/promo-code/promo-code-form/test/promo-code-form.spec.js

Save btn was active, when you was entering "Edit promocode" page. Now it's disabled by default, and only when changes are made, is transformed to active
| ![image](https://user-images.githubusercontent.com/84774115/173333852-1aeaa729-35e5-40b9-94d1-a08c3a89ccc2.png) | ![image](https://user-images.githubusercontent.com/84774115/173333812-e29a6a41-ebec-4eac-bd9a-8a3bd5ef260a.png) |

make save btn disabled when changes were not yet made

---

src/pages/order-item/tabs/general.js

Admin cannot change the payment status when the user pays by card.

button is disabled when payment method is card

---

src/redux/email-questions/email-questions.sagas.js

After answering to the question on sidebar quantity of questions is wrong.
Only after loading correct number is displayed. 
Now it works corectly. Amount of questions changing after answering.
| ![image](https://user-images.githubusercontent.com/83120263/204592878-b9b30345-fc25-4f02-93ad-a4ffd896c041.png) | ![image](https://user-images.githubusercontent.com/83120263/204592965-b24ebbb9-92c6-422a-908b-6512bbb4539b.png) |

Email-question page changed after answering to the question

---

src/components/error-boundary/error-boundary.js
src/pages/error-page/error-page.js

Create posibility to use sidebar  when error appears.
Add route to errors

Sidebar works when error appears

---

src/pages/order-item/tabs/add-product-form/add-product-form.js
src/pages/order-item/tabs/add-product-form/add-product-form.styles.js

When we don't select a product and remove the focus from the input, the error "field cannot be empty" is displayed.
We don't have an error when we select product.
| ![Знімок екрана 2022-12-02 175245](https://user-images.githubusercontent.com/83120263/205334898-d6b8277b-525d-43f7-be6c-630fd7c5edd7.jpg) | ![Знімок екрана 2022-12-02 175501](https://user-images.githubusercontent.com/83120263/205334972-4958a443-a4db-4c4a-9b8a-7db791517b07.jpg)
|![Знімок екрана 2022-12-02 175259](https://user-images.githubusercontent.com/83120263/205334993-9ff5f6a1-587c-47f6-9996-1630c4faaacf.jpg) | ![Знімок екрана 2022-12-02 175522](https://user-images.githubusercontent.com/83120263/205335017-d3edfd …

Fixed error when focus out input with chosen product

---

src/components/draganddrop/slide/slide.js
src/configs/titles.js

Removed 'learn more' link from slider on the Static pages -> Main page -> Slider.
|![image](https://user-images.githubusercontent.com/79856961/207348514-02e01a6a-ad4c-4b76-b7d6-a6e33e840b27.png)|![image](https://user-images.githubusercontent.com/79856961/207348294-1744d366-af13-4b8f-9124-54428b91a0c8.png)|

Removed 'learn more' link from slider

---

src/components/forms/business-page-form/business-page-form.js
src/components/forms/material-about-form/material-about-form.js
src/components/forms/model-form/model-form.js
src/pages/order-item/order-item.js

Fixed "unsaved changes" popup on business pages chaotic appearance and incorrect work of it on 'about material', 'model' and order item' forms.

Fixed "unsaved changes" popup on business pages
